sudo: required
dist: trusty
python: "3.6"
services:
  - docker
env:
  global:
    - IMAGE_NAME=sylvance/kuns-orbit
    - secret: "my-secret-squared"

before_script:
  - docker pull "${IMAGE_NAME}:latest" || true
script:
  - docker build --pull --cache-from "${IMAGE_NAME}:latest" --tag "$IMAGE_NAME" .

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - git_sha="$(git rev-parse --short HEAD)"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${git_sha}"
deploy:
  - provider: script
    script: docker push "${IMAGE_NAME}:latest"
    on:
      branch: master

  - provider: script
    script: docker push "${IMAGE_NAME}:${git_sha}"
    on:
      branch: develop
